package com.weimob.customer.mapper;

import com.weimob.customer.model.Consumer;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ConsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbggenerated Fri Dec 21 12:02:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbggenerated Fri Dec 21 12:02:45 CST 2018
     */
    int insert(Consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbggenerated Fri Dec 21 12:02:45 CST 2018
     */
    Consumer selectByPrimaryKey(Integer id);

    Consumer selectByPid(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbggenerated Fri Dec 21 12:02:45 CST 2018
     */
    List<Consumer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbggenerated Fri Dec 21 12:02:45 CST 2018
     */
    int updateByPrimaryKey(Consumer record);
}