package com.weimob.customer.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Consumer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.id
     *
     * @mbggenerated Fri Dec 21 12:02:45 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_name
     *
     * @mbggenerated Fri Dec 21 12:02:45 CST 2018
     */
    private String consumerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.pid
     *
     * @mbggenerated Fri Dec 21 12:02:45 CST 2018
     */
    private Integer pid;

    public Consumer(String consumerName,Integer pid){
        this.consumerName = consumerName;
        this.pid = pid;
    }

}